import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { neue } from "./(root)/styles/fonts";

import "./globals.css";


// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Student Mentorship Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={neue.className}>{children}</body>
    </html>
  );
}
